### ISSUE TITLE
Build failures

### ISSUE THREAD

**Issue by NuLL3rr0r** [nethershaw/gridcoin#2]
I had gridcoin installed using your repo a few days back on one of my Funtoo systems.

Today, I tried to install it on another installation with the following build errors:

```
$ emerge -avt gridcoin       

These are the packages that would be merged, in reverse order:

Calculating dependencies | * Digest verification failed:
 * /var/lib/layman/gridcoin/net-p2p/gridcoin/gridcoin-9999.ebuild
 * Reason: Filesize does not match recorded size
 * Got: 3239
 * Expected: 3430
 * Missing digest for '/var/lib/layman/gridcoin/net-p2p/gridcoin/gridcoin-3.6.3.0-r2.ebuild'                                                                 ... done!

!!! All ebuilds that could satisfy "gridcoin" have been masked.
!!! One of the following masked packages is required to complete your request:
- net-p2p/gridcoin-9999::gridcoin (masked by: corruption)
- net-p2p/gridcoin-3.6.3.0-r2::gridcoin (masked by: corruption)

For more information, see the MASKED PACKAGES section in the emerge
man page or refer to the Gentoo Handbook.
```

I noticed you had a commit half an hour ago so I reverted that commit and it worked.

Another build error was this:

```
upgrader.cpp:5:17: fatal error: zip.h: No such file or directory
```

So, I emerged dev-libs/libzip and tried again which successeded. I believe libzip must be added as a dependency.

**Comment by commander-derp** [comment]
I experienced the same issue with missing zip.h, however in my investigations I found that the Gridcoin source includes a zip.h, so I think the root of the problem is that it isn't adding the necessary include directory when compiling (and therefore is a problem with the Gridcoin source, not necessarily the ebuild).

Adding a dependency on dev-libs/libzip is an easy workaround, though.

**Comment by dpopchev** [comment]
I also experienced the same issue, but already had dev-libs/libzip emerged.

For the time being I emerged it by 
`emerge --digest -av gridcoin`

**Comment by NuLL3rr0r** [comment]
I forked it at https://github.com/NuLL3rr0r/gridcoin resolved those issues and updated the ebuild to 3.7.5.0 if @commander-derp likes I could make a pull request.

**Comment by nethershaw** [comment]
Thank you for catching this, and for your patience. Sorry for taking so long to notice these.

Since Gentoo prefers to include system libraries at build time, distribution practices suggest that a dependency on the dev-libs/libzip package is the correct solution. It is unclear to me why the upstream developers have chosen to bundle libzip with their source, but in either case a consistent build system with its own libzip (assuming no strict dependency on a particular libzip version) should successfully resolve the dependency on its own. It may be appropriate for upstream to reconsider bundling it.

**Comment by nethershaw** [comment]
I followed up with the Gridcoin developers on Slack. The bundling of libzip is a relic from an earlier time, and no longer appears in the Gridcoin-Research development branch. The removal of these libraries has yet to be merged to the staging or master branches. Even in current builds, no code actually references these parts of the source tree.

I can positively confirm that the libzip library _is_ still a dependency in staging and master, and so the suggestion to add it to the ebuild was correct.

**Comment by NuLL3rr0r** [comment]
@nethershaw  you're welcome. Good to see there's a new release available. I'll check it out.
